name: learn-github-actions
on: [push]
jobs:
 check-bats-version:
  runs-on: ubuntu-latest
  steps:
   - user: actions/checkout@v2
   - user: actions/setup-node@2
     with:
      node-version: '14'
   - run: npm install -g bats
   - run: bats -v